variable "instanceName" {}
variable "region" {}
variable "key_name" {}
variable "subnet_id" {}
variable "ami" {}
variable "instance_type" {}
variable "vpc_id" {}
variable "availability_zone" {}
variable "additional_tags" {}
variable "ports" {}